BEGIN
   FOR cur IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

CREATE TABLE SETURI (
    COD_SET         VARCHAR2(3),
    NUME_SET        VARCHAR2(100) NOT NULL,
    DATA_LANSARE    DATE,
    NUMAR_CARTI     NUMBER(10) NOT NULL,
    URL_IMAGINE_SET VARCHAR2(255) NOT NULL,
    
    CONSTRAINT pk_set PRIMARY KEY (COD_SET),
    CONSTRAINT ck_set_numar_carti CHECK (NUMAR_CARTI > 0)
);

CREATE TABLE CARTI (
    NUME_CARTE     VARCHAR2(100),
    COST_MANA      NUMBER(10),
    RARITATE       VARCHAR2(20),
    LINIE_TIP      VARCHAR2(100) NOT NULL,
    DESCRIERE      VARCHAR2(999) NOT NULL,
    URL_IMAGINE    VARCHAR2(255) NOT NULL,
    PUTERE		   NUMBER(10),
    DURITATE       NUMBER(10),
    LOIALITATE     NUMBER(10),
    APARARE        NUMBER(10),
    NUMAR_DETINUT  NUMBER(10) NOT NULL,
    
    CONSTRAINT pk_carte PRIMARY KEY (NUME_CARTE),
    CONSTRAINT ck_carte_cost_mana CHECK (COST_MANA >= 0),
    CONSTRAINT ck_carte_raritate CHECK (RARITATE IN ('common', 'uncommon', 'rare', 'mythic','bonus')),
    CONSTRAINT ck_carte_putere CHECK (PUTERE >= 0),
    CONSTRAINT ck_carte_duritate CHECK (DURITATE >= 0),
    CONSTRAINT ck_carte_loialitate CHECK (LOIALITATE >= 0),
    CONSTRAINT ck_carte_aparare CHECK (APARARE >= 0),
    CONSTRAINT ck_carte_detinut CHECK (NUMAR_DETINUT >= 0)
);

CREATE TABLE PACHETE (
    ID_PACHET     NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUME_PACHET   VARCHAR2(100) NOT NULL,
    FORMAT_JOC    VARCHAR2(50),
    
    CONSTRAINT ck_pachet_format CHECK (FORMAT_JOC IN ('standard', 'modern', 'commander', 'legacy', 'draft', 'sealed')),
    CONSTRAINT pk_pachet PRIMARY KEY (ID_PACHET)
);


CREATE TABLE LOCATII (
    ID_LOCATIE    NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUME_LOCATIE  VARCHAR2(100) NOT NULL,
    TARA          VARCHAR2(100) NOT NULL,
    ORAS          VARCHAR2(100) NOT NULL,
    STRADA        VARCHAR2(100) NOT NULL,
    NUMAR         VARCHAR2(100) NOT NULL,
    PARTENER_WOTC VARCHAR2(20),

    CONSTRAINT pk_locatie PRIMARY KEY (ID_LOCATIE),
    CONSTRAINT ck_locatie_partener CHECK (PARTENER_WOTC IN ('none', 'core', 'advanced')),
    CONSTRAINT ck_locatie_numar CHECK (NUMAR > 0)
);

CREATE TABLE JUCATORI (
    ID_JUCATOR    NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUME          VARCHAR2(50),
    PRENUME       VARCHAR2(50),
    GAMEID        VARCHAR2(50),
    EMAIL         VARCHAR2(50),
    
    CONSTRAINT pk_jucator PRIMARY KEY (ID_JUCATOR),
    CONSTRAINT uq_jucator_gameid UNIQUE (GAMEID),
    CONSTRAINT uq_jucator_email  UNIQUE (EMAIL),
    CONSTRAINT ck_jucator_email_valid CHECK (EMAIL LIKE '%@%.%')
);

CREATE TABLE EVENIMENTE (
    ID_EVENIMENT   NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUME_EVENIMENT VARCHAR2(100) NOT NULL,
    DATA_EVENIMENT DATE,
    TIP            VARCHAR2(50),
    ID_LOCATIE     NUMBER(5),
    COD_SET        VARCHAR2(3),
    
    CONSTRAINT pk_eveniment PRIMARY KEY (ID_EVENIMENT),
    CONSTRAINT fk_eveniment_locatie FOREIGN KEY (ID_LOCATIE) REFERENCES LOCATII(ID_LOCATIE) ON DELETE CASCADE,
    CONSTRAINT fk_eveniment_set     FOREIGN KEY (COD_SET)    REFERENCES SETURI(COD_SET) ON DELETE CASCADE,
    CONSTRAINT ck_eveniment_tip  CHECK (TIP IN ('constructed', 'limited', 'casual', 'tournament'))
);

CREATE TABLE MECIURI (
    ID_MECI          NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ID_EVENIMENT     NUMBER(5),
    JOCURI_CASTIGATE NUMBER(1),
    JOCURI_PIERDUTE  NUMBER(1), 
    RUNDA            NUMBER(1),
    
    CONSTRAINT pk_meci PRIMARY KEY (ID_MECI),
    CONSTRAINT fk_meci_event FOREIGN KEY (ID_EVENIMENT)  REFERENCES EVENIMENTE(ID_EVENIMENT) ON DELETE CASCADE,
    CONSTRAINT ck_meci_jocuri_castigate CHECK (JOCURI_CASTIGATE >= 0),
    CONSTRAINT ck_meci_jocuri_pierdute CHECK (JOCURI_PIERDUTE >= 0),
    CONSTRAINT ck_meci_runda CHECK (RUNDA > 0)
);

CREATE TABLE CARTI_SETURI (
    COD_SET        VARCHAR2(3),
    NUME_CARTE     VARCHAR2(100),
    NUMAR_COPII    NUMBER(10),
    
    CONSTRAINT pk_carti_seturi PRIMARY KEY (COD_SET, NUME_CARTE),
    CONSTRAINT fk_set_carte FOREIGN KEY (COD_SET) REFERENCES SETURI(COD_SET) ON DELETE CASCADE,
    CONSTRAINT fk_carte_set  FOREIGN KEY (NUME_CARTE) REFERENCES CARTI(NUME_CARTE) ON DELETE CASCADE,
    CONSTRAINT ck_carti_seturi_numar_copii CHECK (NUMAR_COPII >= 0)
);

CREATE TABLE PACHETE_CARTI (
    ID_PACHET      NUMBER(5),
    NUME_CARTE     VARCHAR2(100),
    CANTITATE      NUMBER(2),
    ZONA_PACHET    VARCHAR2(100),
    
    CONSTRAINT pk_pachete_carti PRIMARY KEY (ID_PACHET, NUME_CARTE),
    CONSTRAINT fk_pachet_carte FOREIGN KEY (ID_PACHET) REFERENCES PACHETE(ID_PACHET) ON DELETE CASCADE,
    CONSTRAINT fk_carte_pachet  FOREIGN KEY (NUME_CARTE) REFERENCES CARTI(NUME_CARTE) ON DELETE CASCADE,
    CONSTRAINT ck_pachete_carti_cantitate CHECK (CANTITATE > 0),
    CONSTRAINT ck_pachete_carti_zona_pachet CHECK (ZONA_PACHET IN ('main', 'side'))
);

CREATE TABLE MECIURI_JUCATORI (
    ID_MECI       NUMBER(5),
    ID_JUCATOR    NUMBER(5),
    ROL_JUCATOR   VARCHAR2(20),
    
    CONSTRAINT pk_meciuri_jucatori PRIMARY KEY (ID_MECI, ID_JUCATOR),
    CONSTRAINT fk_meci_jucator FOREIGN KEY (ID_MECI)    REFERENCES MECIURI(ID_MECI) ON DELETE CASCADE,
    CONSTRAINT fk_jucator_meci  FOREIGN KEY (ID_JUCATOR) REFERENCES JUCATORI(ID_JUCATOR) ON DELETE CASCADE,
    CONSTRAINT ck_meciuri_jucatori_rol CHECK (ROL_JUCATOR IN ('friend', 'enemy'))
);

CREATE TABLE PACHETE_MECIURI (
    ID_PACHET           NUMBER(5),
    ID_MECI             NUMBER(5),
    UTILIZAT_DE         VARCHAR2(20),
    
    CONSTRAINT pk_pachet_meci PRIMARY KEY (ID_PACHET, ID_MECI),
    CONSTRAINT fk_pachet_in_meci FOREIGN KEY (ID_PACHET) REFERENCES PACHETE(ID_PACHET) ON DELETE CASCADE,
    CONSTRAINT fk_meci_cu_pachet    FOREIGN KEY (ID_MECI) REFERENCES MECIURI(ID_MECI) ON DELETE CASCADE,
    CONSTRAINT ck_pachet_meci_utilizat_de CHECK (UTILIZAT_DE IN ('friend', 'enemy'))
);

-- Vizualizarea compusa pentru cartile rare
CREATE OR REPLACE VIEW V_PORTOFOLIU_RARE AS
SELECT 
    NUME_CARTE,
    RARITATE,
    NUMAR_DETINUT,
    COST_MANA,
    URL_IMAGINE
FROM CARTI
WHERE RARITATE IN ('rare', 'mythic');

-- Vizualizarea complexa pentru analiza pachetelor
CREATE OR REPLACE VIEW V_ANALIZA_PACHETE AS
SELECT 
    p.ID_PACHET,
    p.NUME_PACHET,
    p.FORMAT_JOC,
    SUM(pc.CANTITATE) AS TOTAL_CARTI,
    SUM(CASE WHEN c.LINIE_TIP LIKE '%Creature%' THEN pc.CANTITATE ELSE 0 END) AS NR_CREATURI,
    SUM(CASE WHEN c.LINIE_TIP NOT LIKE '%Creature%' THEN pc.CANTITATE ELSE 0 END) AS NR_SPELLS,
    ROUND(SUM(c.COST_MANA * pc.CANTITATE) / NULLIF(SUM(pc.CANTITATE), 0), 2) AS MEDIA_MANA_COST

FROM PACHETE p
JOIN PACHETE_CARTI pc ON p.ID_PACHET = pc.ID_PACHET
JOIN CARTI c ON pc.NUME_CARTE = c.NUME_CARTE
GROUP BY p.ID_PACHET, p.NUME_PACHET, p.FORMAT_JOC;

COMMIT;